### ISSUE TITLE
ETA on new release?

### ISSUE THREAD

**Issue by gilmoregrills** [jenkinsci/aws-cloudwatch-logs-publisher-plugin#20]
I would really like that pipeline step, is there any way I can help?

**Comment by TimDuffy** [comment]
Bump! This would be extremely useful for me as well.

**Comment by robinbanbury** [comment]
Any news on when a new release with the pipeline step will be out?

**Comment by rikturnbull** [comment]
Hi @elifarley - is this plugin abandoned? Can we get the latest changes released?
