### ISSUE TITLE
Jenkinsfile integration

### ISSUE THREAD

**Issue by elifarley** [jenkinsci/aws-cloudwatch-logs-publisher-plugin#8]
It should be easy to use this plugin in a Jenkinsfile.

**Comment by waderobson** [comment]
Love this plugin! Thank you for making this available. I would really like to be able to use it in pipelines. I wish I knew java as I would love to help push this through.

**Comment by josedesousa** [comment]
Would really appreciate this feature too

**Comment by alubneuski** [comment]
+1

**Comment by xolotlatoani** [comment]
+1

**Comment by DevOpsMaestro** [comment]
love this plugin.
Could really use the hooks for Pipelines with Jenkinsfile.  
Please also add the hooks so a person can use the Snippet Generator to appropriately create what is needed for the Jenkinsfile.
